//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalFinance
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PersonalFinanceAppEntities : DbContext
    {
        public PersonalFinanceAppEntities()
            : base("name=PersonalFinanceAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User_Accounts> User_Accounts { get; set; }
        public virtual DbSet<User_Transactions> User_Transactions { get; set; }
        public virtual DbSet<User_Items> User_Items { get; set; }
    }
}
