//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalFinance
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Accounts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_Accounts()
        {
            this.User_Transactions = new HashSet<User_Transactions>();
        }
    
        public string AccountID { get; set; }
        public string UserID { get; set; }
        public string AccountName { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string Institution_name { get; set; }
        public string Access_Token { get; set; }
        public string Account_Type { get; set; }
    
        public virtual User_Items User_Items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Transactions> User_Transactions { get; set; }
    }
}
