//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalFinance
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Transactions
    {
        public string TransactionID { get; set; }
        public string AccountID { get; set; }
        public string CategoryID { get; set; }
        public System.DateTime Date { get; set; }
        public string Location_Name { get; set; }
        public string Location_City { get; set; }
        public string Location_State { get; set; }
        public decimal Amount { get; set; }
    
        public virtual User_Accounts User_Accounts { get; set; }
    }
}
