//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalFinance
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Items
    {
        public string ID { get; set; }
        public string Access_Token { get; set; }
        public string Item_ID { get; set; }
    }
}
