//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalFinance
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Finance
    {
        public string UserID { get; set; }
        public decimal Income { get; set; }
        public decimal Fixed_Expenses { get; set; }
    }
}
